name: Deploy Angular App to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: TranspoSyncWeb

      - name: Build Angular app
        run: npm run build -- --base-href /Transpo_Sync_Web/
        working-directory: TranspoSyncWeb

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: TranspoSyncWeb/dist/transpo-sync-web/browser

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
